production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['MYSQL_DATABASE'] %>
  pool: 5
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOSTNAME'] %>
